//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyConfiguration("Retail")]
[assembly: AssemblyCompany("Sound in Theory Ltd")]
[assembly: AssemblyProduct("DynamicImage")]
[assembly: AssemblyCopyright("Copyright ©2010 Sound in Theory Ltd")]
[assembly: AssemblyTrademark("sitdap.com")]
[assembly: ComVisible(false)]

[assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyFileVersion("1.0.0.0")]